name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: 
          xcodebuild clean build 
